root = "."
testdata_dir = "testdata"
tmp_dir = "build"

[build]
  bin = "build/main"
  cmd = "go build -o build/main ./cmd/server/main.go"
  pre_cmd = [
    "go-swagger3 --module-path . --main-file-path ./cmd/server/main.go --output docs/swaggerui/swagger.json --schema-without-pkg"
  ]
  delay = 1000
  exclude_dir = ["assets", "build", "vendor", "testdata", "docs"]
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = "0s"
  log = "build-errors.log"
  stop_on_error = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = true
  main_only = false
  silent = false

[misc]
  clean_on_exit = true

[proxy]
  enabled = true
  app_port = 8000
  proxy_port = 0

[screen]
  clear_on_rebuild = false
  keep_scroll = true
