name: Go

on:
  push:
    branches: 
      - "main"
      - "dev"
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'

  pull_request:
    branches: 
      - "main"
      - "dev"
    paths:
      - '**.go'
      - '**/go.mod'
      - '**/go.sum'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Cache Go modules
      if: github.ref == 'refs/heads/dev'
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: go-mod-${{ runner.os }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          go-mod-${{ runner.os }}

    - name: Build
      run: go build -v cmd

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Test
      run: go test -v ./...
